<?php
return [
		 'PROFILE_IMAGE_PATH'=>'uploads/profile_images/',
		 'PRODUCT_IMAGE_PATH'=>'uploads/product_gallery_images/',
		 'USER_MEDIA_VIDEO_PATH'=>'uploads/user_media/video/',
		 'USER_MEDIA_AUDIO_PATH'=>'uploads/user_media/audio/',
		 'USER_MEDIA_IMAGE_PATH'=>'uploads/user_media/image/',
		 'USER_DOCUMENT_IMAGE_PATH'=>'uploads/user_media/document/',
		 'SITE_PAGES_IMAGE_PATH'=>'uploads/pages-media/',
		 'SITE_PRODUCT_IMAGE'=>'uploads/product-media/',
		 'SITE_IMAGE_PATHS'=> 'public/img/',
		 'CHIPSET_IMAGE_PATHS'=> 'uploads/chipset_images/',
		 'TESTIMONIAL_IMAGE_PATHS'=> 'uploads/testimonial_image/',
	     'HOME_SLIDER_IMAGE_PATHS'=> 'uploads/home_slider/',
	     'HOME_LOGOS_IMAGE_PATHS'=> 'uploads/home_logos/',
	     'HOME_IMAGES_PATH'=> 'uploads/home_images/',
	     'GIFT_CARD_IMAGE'=> 'uploads/giftcard_images/',
		 	 
		 'MESSAGE'=>[
		 	           'INACTIVE_MEMBER_STAFF'=>"You can't login in site panel, please contact to site admin!",
		 	           'ACCESS_DENIED'=>"You are not authorize to access it.",
		 	           'SUCCESS_MESSAGE'=>"Successfully done!",
		 	           'TRY_AGAIN'=>"Something went wrong,Please try again",
		           ],

		   'ADMIN_PAGE_HEADING'=>[
		 	           'ROLE_PERMISSION'=>"Manage Role Permissions",
		           ],

		   'ADMIN_PAGE_TITLE'=>[
		 	           'ROLE_PERMISSION'=>"Role Permissions",
		 	           'MANAGE_CURRENCY_RATES'=>"Manage Currency",
		 	           'ACCESS_DENIED'=>"Access Denied",
		 	           'UPDATECURRENCY'=>"Update Currency",
		 	           'PRODUCT'=>"Products",
		 	           'ADD_PRODUCT'=>"Add Product",
		 	           'PRODUCTCATEGORY'=>"Manage Product Categories",
		 	           'ADD_UPDATE_COUPON'=>"Add/Update Coupon",
		 	           'MANAGE_COUPON'=> 'Manage Coupon',
					   'MANAGE_GIFTCARD'=> 'Manage Gift Card',
		 	           'MANAGE_GRAPHICS'=> 'Manage Graphic Card',
		 	           'MANAGE_DRIVES'=> 'Manage Hard Drives',
		 	           'MANAGE_SCREEN'=> 'Manage Screen Sizes',
		 	           'MANAGE_SSD'=> 'Manage SSD',
		 	           'MANAGE_TYPES'=> 'Manage Types',
		 	           'MANAGE_PROCESSORS'=> 'Manage Processors',
		 	           'MANAGE_RAM'=> 'Manage RAM',
		 	           'ADD_UPDATE_GRAPHIC' => 'Add/Update Graphic Card',
		 	           'ADD_UPDATE_DRIVE' => 'Add/Update Hard Drive',
		 	           'ADD_UPDATE_SCREEN' => 'Add/Update Screen Size',
		 	           'ADD_UPDATE_SSD' => 'Add/Update SSD',
		 	           'ADD_UPDATE_TYPE' => 'Add/Update Type',
		 	           'ADD_UPDATE_PROCESSOR' => 'Add/Update Processor',
		 	           'ADD_UPDATE_RAM' => 'Add/Update RAM',
		 	           'ORDER'=>"Orders",
		 	           'BLOG_POST'=>"Blog Posts",
		 	           'ALL_USERS'=>"Manage Users",
		 	           'USER_INFO'=>"User info",
		 	           'ADD_USER'=>"Add New User",
		 	           'PAGES'=>"All Pages",
		 	           'ADD_UPDATE_PAGES'=>"Aadd & Update Page",
		 	           'SITE_SETTINGS'=>"Site settings",
		 	           'MANAGE_TRANSACTIONS'=>"Manage Transactions",
		 	           'ADD_UPDATE_TRANSLATION'=>"Add Update Translation",
		 	           'MANAGE_ORDERS'=>"Manage Orders",
		 	           'VIEW_ORDER'=>"View Order",
		 	           'BLOG_TITLE'=>" BLOG",
		 	           'MANAGE_SLIDER' => 'Manage Home Slider',
		 	           'MANAGE_LOGO' => 'Manage Home Logo',
		 	           'ALL_LOGOS' => 'All Logos',
		 	           'MANAGE_TESTIMONIAL' => 'Manage Testimonial',
		 	           'ALL_TESIMONIALS' => 'All Testimonials',
		 	           'MANAGE_GETTING' => 'Manage Getting',
		 	           'MANAGE_COLOR_ATTR' => 'Manage Color Attributes',
		 	           'MANAGE_BRAND_ATTR' => 'Manage Brand Attributes',
		 	           'ALL_COLOR_ATTR' => 'All Color Attributes',
		 	           'ALL_GETTINGS' => 'All Gettings',
		 	           'MANAGE_ABOUT' => 'Manage About Us',
		 	           'MANAGE_HOME' => 'Manage Home',
		 	           'MANAGE_CONTACT' => 'Manage Contact Us',
		 	           'MANAGE_CONTACT_REQUEST' => 'Manage Contact Requests',
		 	           'INVESTOR' => 'Manage Investor Page Content',
		 	           'PARTNER' => 'Manage Partner Page Content',
		 	           'ABOUT' => 'Manage About Page Content',
		 	           'PRIVACY_POLICY' => 'Manage Privacy Policy Page Content',
		 	           'TERMS' => 'Manage Terms of Use Content'
		           ],
		 
        ] ;

?>
